name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        no-cache: false
        tags: ghcr.io/uvarc/sticky_test:latest
    -
      name: Image digest
      run: echo $${{ steps.docker_build.outputs.digest }}
      
  notify:
  
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    -
      name: Install awscli
      run: sudo pip install --upgrade pip && pip install awscli
    -
      name: Send SQS message
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DCOS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DCOS_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body '/uvarc/sticky_test' || exit 1;
